## Location (IRRI Los Banos)
latitude = 14.22
elevation = 23
CO2 = 340
ANGSTA = 0.29
ANGSTB = 0.45
FAOF = 1

# Production levels (0 = false or 1 = true)
water_limited = 0
nitrogen_limited = 0

# Start date of model
modelstart = 1992-01-01

# Days after modelstart until emergence
cropstart = 3

# Maximum duration (days)
max_duration = 200

# Establishment: DIRECT-SEED or TRANSPLANT
ESTAB = DIRECT-SEED

# Evapotranspiration method: PENMAN, MAKKINK, or PRIESTLEY TAYLOR
ETMOD = PENMAN
RICETYPE = LOWLAND

SBDUR = 0
TMPSB = 0

# Temperature correction table (DOY, correction)
TMCTB = 0, 0, 366, 0

# Water balance (when water_limited = 1)
WATBAL = PADDY

# Irrigation: 0=rainfed, 2=pond depth, 3=KPa, 6=stage KPa
SWITIR = 0
DVSIMAX = 2.0
IRRI = 75
SLMIN = 3
KPAMIN = 5
WCMIN = 0.30
WL0MIN = 10
WL0DAY = 5
# ISTAGET for SWITIR=6: startDVS, endDVS, KPAMIN (up to 5 stages)
ISTAGET = 0.00, 0.20, 5, 0.65, 0.80, 50, 1.00, 1.20, 5, 1.50, 1.60, 50, 1.70, 1.80, 5


# soil nitrogen
RECNIT = 0.0, 0.30, 0.2, 0.35, 0.4, 0.50, 0.8, 0.75, 1.0, 0.75, 2.5, 0.75
SOILSP = 0.8 ; Soil N mineralization rate (kg N ha-1 d-1)
# nitrogen fertilizer application rate (kg N ha-1 d-1; Y value)
# as a function of days after emergence (d; X value):
FERTIL = 12., 60., 30., 60., 67., 60., 95., 45.

