## Placeholder soil for potential production (water balance not used)
SCODE = POTENTIAL
NL = 1
TKL = 1.0
ZRTMS = 1.0
WL0MX = 0
WL0I = 0
SWITPD = 0
SWITGW = 0
SWITPF = 0
SWITVP = -1
SWITKH = 0
FIXPERC = 0
KST = 0
WCST = 0.3
WCLI = 0.3
RIWCLI = NO
ZWTB = 1, 200, 366, 200
