## Template soil data file for SOILPF soil water balance model.
## File name   : SOILPFIN.DAT
## The PFSOIL water balance keeps soil water tension and soil water
## content at fixed levels as read in this input data file, for 10
## soil layers. One tension value needs to be supplied as function of
## crop development stage or as function of daynumber of year.
## Give code name of soil data file to match the water balance PFSOIL:

SCODE = SOILPF

# ---------------------------------------------------------------*
# 1. Soil moisture tension
# Tension data in kPa as function of development stage (DVS) or
# tension data in kPa as function of day of year (DOY)
# ---------------------------------------------------------------*
# STYPE = 'SDVS' ; Tension data in kPa as function of development stage (DVS)
STYPE = SDAY  ; Tension data in kPa as function of day (DOY)

# If STYPE = 'SDVS', give tension data as PFDVS table:
# first column is DVS (-), second column is tension (kPa)
PFDVS = 0., 10., 0.8, 10., 0.81, 0., 1.20, 0., 1.21, 10., 2.5, 10.

# If STYPE = 'SDAY', give tension data as PFDAY table:
# first column is day (-), second column is tension (kPa)
PFDAY = 0., 100., 50., 100., 51., 100., 365., 100.


# ---------------------------------------------------------------*
# 2. Soil water retention curve
# These data will be used to calculate soil water content from
# the soil water tension data supplied above
# ---------------------------------------------------------------*
# Soil water retention data as table PFCURVE
# first column is water content (m3 m-3), second column is tension (kPa)
# Note: first row should give values at saturation (0 kPa)
# Note: last row should give values at complete dryness (1500 kPa)
PFCURVE = 0., 0.52, 10., 0.48, 100., 0.21, 1500., 0.0001

